name: Cron Job

on:
  schedule:
    - cron: '*/2 * * * *'  # Run every day at midnight UTC

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cron job
        run: |
          # Place your cron job commands here
          echo "Cron job running at $(date)"
          
